# Generated by Django 3.2.9 on 2021-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_lg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='risk',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')], max_length=1),
        ),
    ]
